apiVersion: 1

datasources:
  - uid: prometheus
    name: Prometheus
    orgId: 1
    type: prometheus
    typeName: Prometheus
    access: proxy
    url: http://asgi-monitor.prometheus:9090
    password: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    readOnly: false
    editable: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: TraceID
      httpMethod: POST
  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    access: proxy
    url: http://asgi-monitor.loki:3100
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: $${__value.raw}
      timeInterval: 15s
  - uid: tempo
    orgId: 1
    name: Tempo
    type: tempo
    typeName: Tempo
    access: proxy
    url: http://asgi-monitor.tempo
    password: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki
      tracesToLogs:
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: true
        mapTagNamesEnabled: false
        tags:
          - compose_service
    readOnly: false
    editable: true
